-- ============================================================================
-- Libera edição ao vivo de corsario_status pelo editor.html (novo conjunto "corsario")
-- ============================================================================
-- Até aqui corsario_status/corsario_criterios eram SOMENTE LEITURA no site inteiro —
-- só corsario.html e js/drawer.js liam (SELECT público), sem nenhuma tela de escrita
-- (README.md documentava isso explicitamente). Este script libera escrita em
-- corsario_status (status/observação por iniciativa×critério), seguindo o MESMO padrão
-- de token compartilhado das outras tabelas (tools/sql/PADRAO_TABELA.md).
--
-- corsario_criterios (a lista dos 19 critérios: chave/rótulo/grupo/ordem) CONTINUA
-- somente leitura — este ciclo é só pra editar os VALORES (status por iniciativa), que é
-- o que muda no dia a dia; adicionar/renomear critério é operação rara e mais estrutural,
-- fica de fora de propósito (mexer direto no Supabase se algum dia for preciso).
--
-- ORDEM DE EXECUÇÃO: depois de 2026-08_protecao_escrita.sql (token) e
-- 2026-08_auditoria.sql (cc_audit()) — os dois já devem estar rodados em produção.
--
-- DIFERENÇA importante em relação às migrações anteriores (2026-08_migracao_modo_edicao.sql):
-- lá as 4 tabelas eram CRIADAS do zero (CREATE TABLE), aqui corsario_status já EXISTE em
-- produção com dado real (hoje 28 iniciativas × até 19 critérios). Por isso todo passo
-- abaixo é defensivo (IF NOT EXISTS / checagem antes de alterar) — não presume nada sobre
-- colunas que a gente não criou e não pode inspecionar por aqui. Rode a seção 0 primeiro
-- e confira a saída antes de seguir, se quiser conferir o que já existe.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 0) Diagnóstico (informativo, não altera nada) — confira as colunas atuais antes de
--    prosseguir, se quiser. Pode pular direto pra seção 1.
-- ---------------------------------------------------------------------------
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'corsario_status'
ORDER BY ordinal_position;


-- ---------------------------------------------------------------------------
-- 1) Garante uma chave primária estável (`id`) — precisa existir pra: (a) o editor
--    conseguir mirar UPDATE numa linha específica sem ambiguidade, (b) cc_audit()
--    conseguir preencher registro_id (usa to_jsonb(NEW)->>'id', que fica NULL — e
--    quebra o INSERT no log, por causa do NOT NULL — se a coluna não existir).
--    Defensivo: só adiciona a coluna se faltar; só promove a PRIMARY KEY se a tabela
--    ainda não tiver nenhuma (não mexe se já houver uma PK, seja ela qual for).
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'corsario_status' AND column_name = 'id'
  ) THEN
    ALTER TABLE public.corsario_status ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_schema = 'public' AND table_name = 'corsario_status' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE public.corsario_status ADD PRIMARY KEY (id);
  END IF;
END $$;

-- coluna de autoria (mesmo nome/padrão de meta_inovacao_pessoas/projetos/etc., P10) —
-- cc_audit() já sabe ler "updated_by" via to_jsonb(NEW)->>'updated_by'.
ALTER TABLE public.corsario_status ADD COLUMN IF NOT EXISTS updated_by text;


-- ---------------------------------------------------------------------------
-- 2) RLS — normaliza pro padrão do projeto (tools/sql/PADRAO_TABELA.md): remove
--    qualquer policy pré-existente (nome desconhecido daqui) e recria do zero com
--    SELECT público + INSERT/UPDATE por token. corsario_criterios NÃO entra aqui —
--    continua só com a policy de SELECT que já tinha, intocada.
-- ---------------------------------------------------------------------------
DO $$
DECLARE pol RECORD;
BEGIN
  FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'corsario_status'
  LOOP EXECUTE format('DROP POLICY IF EXISTS %I ON public.corsario_status', pol.policyname); END LOOP;
END $$;

ALTER TABLE public.corsario_status ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.corsario_status TO anon, authenticated;

CREATE POLICY "cc_select_publico" ON public.corsario_status FOR SELECT TO anon USING (true);
CREATE POLICY "cc_token_insert" ON public.corsario_status FOR INSERT TO anon
  WITH CHECK (current_setting('request.headers', true)::json->>'x-cc-token' = '90bb649c-0a59-43b1-b486-17ec58f99108');
CREATE POLICY "cc_token_update" ON public.corsario_status FOR UPDATE TO anon
  USING (current_setting('request.headers', true)::json->>'x-cc-token' = '90bb649c-0a59-43b1-b486-17ec58f99108')
  WITH CHECK (current_setting('request.headers', true)::json->>'x-cc-token' = '90bb649c-0a59-43b1-b486-17ec58f99108');


-- ---------------------------------------------------------------------------
-- 3) Auditoria (item 3.4/P13) — reaproveita cc_audit() (2026-08_auditoria.sql).
--    CREATE OR REPLACE aqui de novo só pra este script funcionar sozinho se rodar
--    fora de ordem (idêntico ao que 2026-08_migracao_modo_edicao.sql já faz).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cc_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_autor text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_autor := COALESCE(to_jsonb(OLD)->>'updated_by', to_jsonb(OLD)->>'atualizado_por', current_setting('request.headers', true)::json->>'x-cc-editor');
    INSERT INTO public.meta_inovacao_audit_log (tabela, registro_id, operacao, valor_anterior, valor_novo, autor)
    VALUES (TG_TABLE_NAME, to_jsonb(OLD)->>'id', TG_OP, to_jsonb(OLD), NULL, v_autor);
    RETURN OLD;
  ELSIF TG_OP = 'UPDATE' THEN
    v_autor := COALESCE(to_jsonb(NEW)->>'updated_by', to_jsonb(NEW)->>'atualizado_por', current_setting('request.headers', true)::json->>'x-cc-editor');
    INSERT INTO public.meta_inovacao_audit_log (tabela, registro_id, operacao, valor_anterior, valor_novo, autor)
    VALUES (TG_TABLE_NAME, to_jsonb(NEW)->>'id', TG_OP, to_jsonb(OLD), to_jsonb(NEW), v_autor);
    RETURN NEW;
  ELSE
    v_autor := COALESCE(to_jsonb(NEW)->>'updated_by', to_jsonb(NEW)->>'atualizado_por', current_setting('request.headers', true)::json->>'x-cc-editor');
    INSERT INTO public.meta_inovacao_audit_log (tabela, registro_id, operacao, valor_anterior, valor_novo, autor)
    VALUES (TG_TABLE_NAME, to_jsonb(NEW)->>'id', TG_OP, NULL, to_jsonb(NEW), v_autor);
    RETURN NEW;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS cc_audit_corsario_status ON public.corsario_status;
CREATE TRIGGER cc_audit_corsario_status
  AFTER INSERT OR UPDATE OR DELETE ON public.corsario_status
  FOR EACH ROW EXECUTE FUNCTION public.cc_audit();


-- ---------------------------------------------------------------------------
-- 4) Recarrega o cache de schema do PostgREST — SEM ISSO a API continua "achando" que
--    id/updated_by não existem mesmo depois do ALTER TABLE acima (DDL feito pelo SQL
--    Editor não avisa o PostgREST sozinho), e toda escrita falha com
--    PGRST204 "Could not find the '<coluna>' column ... in the schema cache" mesmo com
--    RLS/GRANT corretos. Descoberto rodando este script em produção pela 1ª vez — quem
--    rodar de novo (ou aplicar o mesmo padrão numa tabela nova) precisa deste passo.
-- ---------------------------------------------------------------------------
NOTIFY pgrst, 'reload schema';


-- ---------------------------------------------------------------------------
-- Pra REVERTER (na ordem inversa):
--   DROP TRIGGER IF EXISTS cc_audit_corsario_status ON public.corsario_status;
--   DROP POLICY IF EXISTS "cc_token_update" ON public.corsario_status;
--   DROP POLICY IF EXISTS "cc_token_insert" ON public.corsario_status;
--   REVOKE INSERT, UPDATE ON public.corsario_status FROM anon, authenticated;
--   -- (updated_by e a PK/id NÃO são desfeitos por padrão — remover só se tiver certeza
--   --  de que nada mais passou a depender deles; a leitura de corsario.html não usa
--   --  nenhum dos dois, então reverter é seguro se for preciso.)
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- Verificação — deve rodar sem erro; total de linhas deve bater com o que
-- corsario.html já mostra hoje (28 iniciativas × até 19 critérios cada).
-- ---------------------------------------------------------------------------
SELECT count(*) AS total_linhas_corsario_status FROM public.corsario_status;
SELECT count(DISTINCT iniciativa) AS total_iniciativas FROM public.corsario_status;
